#! /bin/bash

# ticker dependsOn ReadMe.txt, which ticker will update
# whenever it is run.  This will cause ticker's updater to be
# fired each time its output is requested.

# Sleep 1 second to ensure that the modification time is detectable
# on the next request:
sleep 1
touch ReadMe.txt

