#! /usr/bin/perl -w

# This script will be invoked by run-test.perl as:
#
#	cd '$TESTDIR'
# 	test-script '$DOCUMENT_ROOT'
#
# where $TESTDIR is the full path of the nnnn numbered test directory
# that is being tested, and $DOCUMENT_ROOT is the full path
# of the RDF Pipeline's Apache DOCUMENT_ROOT.
#
# You may customize any part of this script as needed for this test,
# though the most commonly customized part is marked "CUSTOMIZE HERE".  
# The script must exit(0) iff the test passes.

use strict;

my $wwwDir = shift @ARGV || $ENV{DOCUMENT_ROOT} || die;
# Ensure this env var is set, so that pipeline-request.perl can find it:
$ENV{DOCUMENT_ROOT} = $wwwDir;	

############ CUSTOMIZE HERE ################
# Make sure ReadMe.txt has a fresh timestamp:
!system("touch '$wwwDir/node/ReadMe.txt'") or die;
# This test appends to hellos.txt, so recreate it:
!system("echo 'BEGIN' > '$wwwDir/node/hellos.txt'") or die;

# Invoke the URL, concatenating its output to $wwwDir/test/testout :
my $testUrl = 'http://localhost/node/hello';

# Requesting the first time should produce ONE line of "hello" output:
!system("../../helpers/pipeline-request.perl GET '$testUrl'") or die;

# Requesting the second time should produce TWO lines of "hello" output:
!system("../../helpers/pipeline-request.perl GET '$testUrl'") or die;
############################################

exit 0;

