#! /usr/bin/perl -w

# This script will be invoked by run-test.perl as:
#
#	cd '$TESTDIR'
# 	test-script '$RDF_PIPELINE_WWW_DIR'
#
# where $TESTDIR is the full path of the nnnn numbered test directory
# that is being tested, and $RDF_PIPELINE_WWW_DIR is the full path
# of the RDF Pipeline's Apache DOCUMENT_ROOT.
#
# You may customize any part of this script as needed for this test,
# though the most commonly customized part is marked "CUSTOMIZE HERE".  
# The script must exit(0) iff the test passes.

use strict;

my $wwwDir = shift @ARGV || $ENV{RDF_PIPELINE_WWW_DIR} || die;
# Ensure this env var is set, so that pipeline-request.perl can find it:
$ENV{RDF_PIPELINE_WWW_DIR} = $wwwDir;	

############ CUSTOMIZE HERE ################
# NOTE: This test compares detailed debugging output.  It is useful in
# helping to see what is affected when you make a code change. 
# However, because it generates such detailed information it would
# be difficult to make it produce the exact same output from one
# installation to another and from one run to another.  That 
# would require filtering out lots of unimportant
# differences, and for the moment it is not worth spending the
# time to do that.   Hence the warning below, that this test
# will normally fail.
warn "This test will normally fail, and that is okay.  See test-script for explanation.\n";
# Invoke the URL, concatenating its output to $wwwDir/test/testout :
# First, invoke with normal debug setting, to get to stable state:
my $testUrl = 'http://localhost/node/UPPERWILLIES?debug=$DEBUG_CHANGES';
!system("../../helpers/pipeline-request.perl GET '$testUrl'") or die;
# Invoke again with debug DETAILS for some 304 responses:
$testUrl = 'http://localhost/node/UPPERWILLIES?debug=$DEBUG_DETAILS';
!system("../../helpers/pipeline-request.perl GET '$testUrl'") or die;
# Try to reset the debug level.  This may not work because of multiple
# apache threads using different memory.
$testUrl = 'http://localhost/node/UPPERWILLIES?debug=$DEBUG_CHANGES';
!system("../../helpers/pipeline-request.perl GET '$testUrl'") or die;
############################################

exit 0;

